"""Create shipping_rates table

Revision ID: 016c19043bfd
Revises: 5c5aa652710b
Create Date: 2024-06-07 16:58:46.202732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016c19043bfd'
down_revision = '5c5aa652710b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pounds', sa.String(length=10), nullable=False),
    sa.Column('usd', sa.Float(), nullable=False),
    sa.Column('jmd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pounds')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    op.drop_table('shipping_rates')
    # ### end Alembic commands ###
