"""empty message

Revision ID: 6afd1e42d27b
Revises: 016c19043bfd
Create Date: 2024-06-08 22:09:16.959460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6afd1e42d27b'
down_revision = '016c19043bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=15), nullable=False),
    sa.Column('id_type', sa.String(length=50), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorized_pickups')
    # ### end Alembic commands ###
