"""empty message

Revision ID: 71918d9249b0
Revises: 6afd1e42d27b
Create Date: 2024-06-09 13:38:54.437434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71918d9249b0'
down_revision = '6afd1e42d27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prealerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=50), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('invoice', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prealerts')
    # ### end Alembic commands ###
